const companyData = {
	employees: [
		{
			id: 1,
			name: 'John Doe',
			age: 20,
			hireDate: '2020-01-01',
			terminationDate: null,
			ethnicity: 'White',
			gender: 'Male',
			veteranStatus: 'No Service',
			department: 'Sales',
			division: 'Onboarding',
			employmentStatus: 'Part-Time',
			location: 'Austin, TX',
			jobTitle: 'Sales Onboarder',
		},
		{
			id: 2,
			name: 'Jane Doe',
			age: 44,
			hireDate: '2010-01-01',
			terminationDate: '2020-01-01',
			ethnicity: 'Asian',
			gender: 'Female',
			veteranStatus: 'Retired',
			department: 'Engineering',
			division: 'Operations',
			employmentStatus: 'Full Time',
			location: 'SLC, UT',
			jobTitle: 'Site Reliability Engineer',
		},
		{
			id: 3,
			name: 'John Smith',
			age: 17,
			hireDate: '2020-01-01',
			terminationDate: null,
			ethnicity: 'Hispanic',
			gender: 'Male',
			veteranStatus: 'No Service',
			department: 'Engineering',
			division: 'Operations',
			employmentStatus: 'Full Time',
			location: 'SLC, UT',
			jobTitle: 'Site Reliability Engineer',
		},
		{
			id: 4,
			name: 'Jane Smith',
			age: 99,
			hireDate: '2020-01-01',
			terminationDate: '2023-01-01',
			ethnicity: 'Hispanic',
			gender: 'Female',
			veteranStatus: 'No Service',
			department: 'Engineering',
			division: 'Development',
			employmentStatus: 'Full Time',
			location: 'SLC, UT',
			jobTitle: 'Software Engineer',
		},
	]
}

export default companyData;
